version: 2.1
orbs:
  slack: circleci/slack@4.12.5
  node: circleci/node@5.1.0
jobs:
  lint_and_unit_test: 
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run format
          name: run lint
      - run:
          command: npm run test
          name: Run tests
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          mentions: 'flamberge1191'
          template: success_tagged_deploy_1
workflows:
  pipeline:
    jobs:
      - lint_and_unit_test
      - notify:
          context: slack-secrets