
import './globals.css';

export const metadata = {
  title: 'パワプロ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="ja">
        <body
          className={`font-noto`}
        >
          {children}
        </body>
      </html>
    </>
  );
}
