import './globals.css';
import { Noto_Sans_JP } from 'next/font/google';

const Noto_Sans_JP_normal = Noto_Sans_JP({
  weight: ['400','700'],
  display: 'swap',
  subsets: ["latin"],
  preload: false,
});

export const metadata = {
  title: 'パワプロ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="ja">
        <body className={Noto_Sans_JP_normal.className}>{children}</body>
      </html>
    </>
  );
}
