import Header from '@/components/header';
import './globals.css';
import Footer from '@/components/footer';

export const metadata = {
  title: 'パワプロ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang='ja'>
        <body
        >
          <Header/>
          {children}
          <Footer />
        </body>
      </html>
    </>
  );
}
